modLoader="javafml"
loaderVersion="[25,)"
issueTrackerURL="http://github.com/xfl03/MoreCrashInfo/issues"
[[mods]]
modId="crashmaker"
version="1.1.0"
displayName="CrashMaker"
displayURL="http://github.com/xfl03/MoreCrashInfo"
credits=""
authors="xfl03"
license="GPL-3.0-only"
description='''
A test mod for MoreCrashInfo, which will make game crash.
'''
[[dependencies.morecrashinfo]]
    modId="forge"
    mandatory=true
    versionRange="[25.0.216,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.morecrashinfo]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.13.2,)"
    ordering="NONE"
    side="BOTH"